// photos-share additions to the album page: the invite dialog (with the
// owner's invite settings) and adding photos. Uploads are only wired up when
// the server rendered the #ipp-upload block (the viewer can add to the album).

import { createUploader, uploadsAvailable } from './uploader.js'

interface UploadConfig {
  albumId: string
  maxBytes: number
  lane?: 'lan' | 'internet'
}

const $ = <T extends HTMLElement>(id: string) => document.getElementById(id) as T | null
// Phones get the native share sheet (WhatsApp etc.) instead of copy
const nativeShare = typeof navigator.share === 'function' && matchMedia('(pointer: coarse)').matches

async function copyText (input: HTMLInputElement | null) {
  const text = input?.value || location.href
  try {
    await navigator.clipboard.writeText(text)
  } catch (e) {
    input?.select()
    document.execCommand('copy')
  }
}

// ----- invite dialog --------------------------------------------------------

function setupInvite () {
  const dialog = $<HTMLDialogElement>('share-dialog')
  const open = $<HTMLButtonElement>('share-open')
  if (!dialog || !open) return
  const url = $<HTMLInputElement>('share-url')
  const copy = $<HTMLButtonElement>('share-copy')

  open.addEventListener('click', () => dialog.showModal())
  $('share-close')?.addEventListener('click', () => dialog.close())
  // Click on the backdrop closes it
  dialog.addEventListener('click', (e) => { if (e.target === dialog) dialog.close() })

  copy?.addEventListener('click', async () => {
    if (nativeShare) {
      try {
        await navigator.share({ title: document.title, text: 'Join my album', url: url?.value || location.href })
        return
      } catch (e) {
        if ((e as Error).name === 'AbortError') return
      }
    }
    await copyText(url)
    copy.textContent = 'Copied!'
    setTimeout(() => { copy.textContent = 'Copy link' }, 2000)
  })
  if (nativeShare && copy) copy.textContent = 'Send link'

  const form = $<HTMLFormElement>('invite-form')
  const save = $<HTMLButtonElement>('invite-save')
  const error = $<HTMLElement>('invite-error')
  if (!form || !save) return
  form.addEventListener('submit', async (e) => {
    e.preventDefault()
    if (error) error.hidden = true
    save.disabled = true
    save.textContent = 'Saving…'
    try {
      const res = await fetch('/api/albums/' + save.dataset.album + '/invite', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'X-Requested-With': 'photos-share' },
        body: JSON.stringify({
          allowUpload: $<HTMLInputElement>('invite-allow-upload')?.checked,
          allowDownload: $<HTMLInputElement>('invite-allow-download')?.checked,
          slug: $<HTMLInputElement>('invite-slug')?.value.trim() || ''
        })
      })
      const data = await res.json().catch(() => ({}))
      if (!res.ok) throw new Error(data.error || 'Couldn\'t save. Try again.')
      if (url) url.value = data.url
      const qr = $('share-qr')
      if (qr) qr.innerHTML = data.qrSvg // SVG generated by the server's qrcode library
      // Keep the address bar on the album's current link
      if (data.path && data.path !== location.pathname) history.replaceState(null, '', data.path)
      save.textContent = 'Saved'
      setTimeout(() => { save.textContent = 'Save settings' }, 1800)
    } catch (err) {
      if (error) {
        error.textContent = (err as Error).message
        error.hidden = false
      }
      save.textContent = 'Save settings'
    } finally {
      save.disabled = false
    }
  })
}

// ----- adding photos --------------------------------------------------------

function setupUpload () {
  const cfgEl = document.getElementById('ipp-upload')
  if (!cfgEl || !uploadsAvailable()) return
  const cfg: UploadConfig = JSON.parse(cfgEl.textContent || '{}')
  const input = $<HTMLInputElement>('upload-input')
  const folderInput = $<HTMLInputElement>('folder-input')
  if (!input) return

  const uploader = createUploader({
    maxBytes: cfg.maxBytes,
    doneTitle: (done, failed) => {
      const noun = done === 1 ? 'photo' : 'photos'
      return failed ? `${done} ${noun} added, ${failed} didn't make it` : `${done} ${noun} added!`
    }
  })

  $('add-photos')?.addEventListener('click', () => input.click())
  $('add-folder')?.addEventListener('click', () => folderInput?.click())
  $('empty-album')?.addEventListener('click', () => input.click())
  $('upload-more')?.addEventListener('click', () => input.click())
  $('upload-view')?.addEventListener('click', () => location.reload())

  const MEDIA = /\.(heic|heif|dng|cr2|cr3|nef|arw|raf|orf|rw2|mov|mp4|m4v|3gp|mts)$/i
  for (const el of [input, folderInput]) {
    el?.addEventListener('change', () => {
      // Folder picks include everything; keep photos and videos only
      const files = Array.from(el.files || []).filter(f => /^(image|video)\//.test(f.type) || MEDIA.test(f.name))
      el.value = ''
      if (files.length) uploader.add(files, { mode: 'member', albumId: cfg.albumId })
    })
  }
}

setupInvite()
setupUpload()
